import { UITheme } from '@/types/cms';

// ==============================
// Default Values (fallback) — safe for client & server
// ==============================

export const DEFAULT_THEME: UITheme = {
  primary_color: '#1152d4',
  secondary_color: '#3b82f6',
  background_color: '#f6f7f8',
  text_color: '#0f172a',
  heading_font: 'Sora',
  body_font: 'Public Sans',
  button_radius: 8,
  card_radius: 8,
  card_bg_color: '#ffffff',
  card_border_color: '#e7edf3',
  search_bg_color: '#f1f5f9',
  search_text_color: '#64748b',
  account_bg_color: '#ffffff',
  account_text_color: '#0f172a',
};

export const DEFAULT_COPY: Record<string, string> = {
  nav_home: 'Home',
  nav_menu: 'Menu',
  nav_how_to_order: 'Cara Pesan',
  nav_account: 'Account',
  search_placeholder: 'Cari donat...',
  cta_search: 'Cari',
  hero_title: 'HR-One Donuts',
  hero_subtitle: 'Resep Tradisional, Rasa Internasional',
  banner_1_label: 'SMS',
  banner_1_title: 'Selasa Mega Sale',
  banner_1_subtitle: 'Diskon s.d 50%',
  banner_2_label: 'Jumat Berkah',
  banner_2_title: 'Beli 1 Lusin',
  banner_2_subtitle: 'Gratis 2 Donat',
  banner_3_label: 'Menu Spesial',
  banner_3_title: 'Cek Promo Hari Ini',
  banner_3_subtitle: 'Mulai Rp 10rb',
  section_catalog: 'Pilihan Terbaik',
  section_catalog_desc: 'Recommended daily delights for you',
  section_flash_sale_subtitle: 'Penawaran Terbatas',
  cta_view_all: 'Lihat Semua',
  cta_view_promo: 'Lihat Promo',
  category_all: 'Semua',
  cta_add_cart: '+ Keranjang',
  cta_buy: 'Beli Sekarang',
  loading_add_cart: 'Sabar ya...',
  sold_label: 'Terjual',
  badge_promo: 'PROMO',
  badge_limited: 'LIMITED',
  badge_bestseller: 'TERLARIS',
  footer_copyright: '© 2024 HR-One Donuts. All rights reserved.',
  footer_navigation: 'Navigasi',
  footer_help: 'Bantuan',
  footer_quicklinks: 'Quick Links',
  footer_support: 'Customer Support',
  footer_contact: 'Hubungi Kami',
  empty_products: 'Belum ada produk aktif.',
  empty_category: 'Tidak ada produk di kategori ini.',
};
